import { Equipment, ExerciseDifficulty, ExercisePerformanceMode, LoadEntryConvention, MovementPattern, MuscleGroup, PrismaClient } from '@prisma/client';
import { normalizeExerciseSearch } from '@machi-gym/contracts';

type Entry = {
  name: string; slug: string; primaryMuscleGroup: MuscleGroup; secondaryMuscleGroups: MuscleGroup[];
  equipment: Equipment[]; movementPattern: MovementPattern; difficulty: ExerciseDifficulty;
  description: string; instructions: string; commonMistakes: string; aliases?: string[];
  performanceMode?: ExercisePerformanceMode; loadEntryConvention?: LoadEntryConvention | null; loadMultiplier?: number;
};
const M = MuscleGroup; const E = Equipment; const P = MovementPattern;
const basic = ExerciseDifficulty.BEGINNER; const intermediate = ExerciseDifficulty.INTERMEDIATE;
export const exerciseSeed: Entry[] = [
  { name: 'Press de banca con barra', slug: 'press-banca-barra', primaryMuscleGroup: M.CHEST, secondaryMuscleGroups: [M.TRICEPS, M.SHOULDERS], equipment: [E.BARBELL, E.BENCH], movementPattern: P.HORIZONTAL_PUSH, difficulty: intermediate, description: 'Empuje horizontal con barra desde un banco plano, con apoyo estable de pies y espalda.', instructions: 'Apoyá la espalda y los pies; bajá la barra con control hasta el pecho y empujá sin perder estabilidad.', commonMistakes: 'Rebotar la barra en el pecho o levantar la cadera.', aliases: ['press de pecho', 'bench press'] },
  { name: 'Press inclinado con mancuernas', slug: 'press-inclinado-mancuernas', primaryMuscleGroup: M.CHEST, secondaryMuscleGroups: [M.SHOULDERS, M.TRICEPS], equipment: [E.DUMBBELL, E.BENCH], movementPattern: P.HORIZONTAL_PUSH, difficulty: intermediate, description: 'Empuje en banco inclinado con una mancuerna por mano y recorrido controlado.', instructions: 'Apoyá la espalda en el banco inclinado; llevá las mancuernas hacia arriba y bajalas de manera pareja.', commonMistakes: 'Arquear demasiado la espalda o juntar las mancuernas con un golpe.', loadEntryConvention: LoadEntryConvention.PER_IMPLEMENT, loadMultiplier: 2 },
  { name: 'Flexiones de brazos', slug: 'flexiones-brazos', primaryMuscleGroup: M.CHEST, secondaryMuscleGroups: [M.TRICEPS, M.SHOULDERS], equipment: [E.BODYWEIGHT], movementPattern: P.HORIZONTAL_PUSH, difficulty: basic, description: 'Empuje horizontal con el peso corporal y el cuerpo alineado desde hombros hasta pies.', instructions: 'Colocá las manos bajo los hombros; flexioná los codos con control y empujá manteniendo el tronco estable.', commonMistakes: 'Dejar caer la cadera o separar demasiado los codos.', aliases: ['lagartijas', 'push ups'], performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
  { name: 'Press militar con barra', slug: 'press-militar-barra', primaryMuscleGroup: M.SHOULDERS, secondaryMuscleGroups: [M.TRICEPS, M.CORE], equipment: [E.BARBELL], movementPattern: P.VERTICAL_PUSH, difficulty: intermediate, description: 'Empuje vertical de barra con el tronco firme y recorrido por encima de la cabeza.', instructions: 'Partí con la barra a la altura superior del pecho; empujá verticalmente y bajá sin perder el control.', commonMistakes: 'Extender la espalda para compensar o llevar la barra muy lejos del cuerpo.' },
  { name: 'Elevaciones laterales con mancuernas', slug: 'elevaciones-laterales', primaryMuscleGroup: M.SHOULDERS, secondaryMuscleGroups: [], equipment: [E.DUMBBELL], movementPattern: P.ISOLATION, difficulty: basic, description: 'Elevación lateral de una mancuerna en cada mano para trabajar los hombros.', instructions: 'Elevá los brazos hacia los lados con los codos suaves y descendé despacio sin balancear el tronco.', commonMistakes: 'Usar impulso del cuerpo o subir con tensión en el cuello.', loadEntryConvention: LoadEntryConvention.PER_IMPLEMENT, loadMultiplier: 2 },
  { name: 'Dominadas', slug: 'dominadas', primaryMuscleGroup: M.BACK, secondaryMuscleGroups: [M.BICEPS, M.FOREARMS], equipment: [E.PULL_UP_BAR, E.BODYWEIGHT], movementPattern: P.VERTICAL_PULL, difficulty: intermediate, description: 'Tracción vertical con peso corporal desde una barra fija y descenso controlado.', instructions: 'Sujetá la barra; llevá el pecho hacia arriba flexionando los codos y descendé sin perder la postura.', commonMistakes: 'Balancear las piernas o dejar caer el cuerpo en la bajada.', aliases: ['pull ups'], performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
  { name: 'Remo con barra', slug: 'remo-barra', primaryMuscleGroup: M.BACK, secondaryMuscleGroups: [M.BICEPS, M.LOWER_BACK], equipment: [E.BARBELL], movementPattern: P.HORIZONTAL_PULL, difficulty: intermediate, description: 'Tracción horizontal de barra con bisagra de cadera y tronco estable.', instructions: 'Incliná el tronco desde la cadera, sostené la espalda estable y acercá la barra al abdomen con control.', commonMistakes: 'Redondear la espalda o levantar el pecho con cada repetición.' },
  { name: 'Jalón al pecho en polea', slug: 'jalon-pecho-polea', primaryMuscleGroup: M.BACK, secondaryMuscleGroups: [M.BICEPS], equipment: [E.CABLE, E.MACHINE], movementPattern: P.VERTICAL_PULL, difficulty: basic, description: 'Tracción vertical en polea hacia la parte superior del pecho.', instructions: 'Sentate con los muslos sujetos; bajá la barra al pecho llevando los codos hacia abajo y subí despacio.', commonMistakes: 'Tirar la barra detrás de la nuca o usar un balanceo excesivo.', aliases: ['lat pulldown'], loadEntryConvention: LoadEntryConvention.MACHINE_STACK },
  { name: 'Remo sentado en polea', slug: 'remo-sentado-polea', primaryMuscleGroup: M.BACK, secondaryMuscleGroups: [M.BICEPS], equipment: [E.CABLE], movementPattern: P.HORIZONTAL_PULL, difficulty: basic, description: 'Tracción horizontal sentado con cable y recorrido estable.', instructions: 'Mantené el tronco erguido; llevá el agarre hacia el abdomen y extendé los brazos con control.', commonMistakes: 'Mover el torso hacia adelante y atrás en lugar de tirar con los brazos.', loadEntryConvention: LoadEntryConvention.MACHINE_STACK },
  { name: 'Curl de bíceps con mancuernas', slug: 'curl-biceps-mancuernas', primaryMuscleGroup: M.BICEPS, secondaryMuscleGroups: [M.FOREARMS], equipment: [E.DUMBBELL], movementPattern: P.ISOLATION, difficulty: basic, description: 'Flexión de codos con una mancuerna por mano y brazos cerca del tronco.', instructions: 'Flexioná los codos sin mover los hombros y bajá lentamente hasta extender los brazos de forma cómoda.', commonMistakes: 'Balancear el torso o adelantar los hombros para levantar más peso.', loadEntryConvention: LoadEntryConvention.PER_IMPLEMENT, loadMultiplier: 2 },
  { name: 'Extensión de tríceps en polea', slug: 'extension-triceps-polea', primaryMuscleGroup: M.TRICEPS, secondaryMuscleGroups: [], equipment: [E.CABLE], movementPattern: P.ISOLATION, difficulty: basic, description: 'Extensión de codos con polea alta y brazos próximos al cuerpo.', instructions: 'Mantené los codos junto al torso; extendé los brazos hacia abajo y volvé con control.', commonMistakes: 'Separar los codos del cuerpo o inclinar el tronco en cada repetición.', loadEntryConvention: LoadEntryConvention.MACHINE_STACK },
  { name: 'Sentadilla trasera con barra', slug: 'sentadilla-trasera-barra', primaryMuscleGroup: M.QUADRICEPS, secondaryMuscleGroups: [M.GLUTES, M.HAMSTRINGS], equipment: [E.BARBELL], movementPattern: P.SQUAT, difficulty: intermediate, description: 'Sentadilla con barra apoyada sobre la parte alta de la espalda y pies firmes.', instructions: 'Flexioná caderas y rodillas manteniendo el apoyo de los pies; levantate empujando el suelo.', commonMistakes: 'Perder el apoyo del pie o dejar que la espalda se redondee.' },
  { name: 'Sentadilla goblet', slug: 'sentadilla-goblet', primaryMuscleGroup: M.QUADRICEPS, secondaryMuscleGroups: [M.GLUTES, M.CORE], equipment: [E.KETTLEBELL], movementPattern: P.SQUAT, difficulty: basic, description: 'Sentadilla con una pesa sostenida frente al pecho para practicar un descenso controlado.', instructions: 'Sostené la pesa cerca del pecho, bajá entre las piernas y levantate manteniendo los pies apoyados.', commonMistakes: 'Separar la pesa del cuerpo o despegar los talones del suelo.' },
  { name: 'Prensa de piernas', slug: 'prensa-piernas', primaryMuscleGroup: M.QUADRICEPS, secondaryMuscleGroups: [M.GLUTES, M.HAMSTRINGS], equipment: [E.MACHINE], movementPattern: P.SQUAT, difficulty: basic, description: 'Empuje de plataforma guiada con pies estables y espalda apoyada.', instructions: 'Ajustá el asiento, flexioná las piernas dentro de un recorrido cómodo y empujá sin bloquear bruscamente las rodillas.', commonMistakes: 'Despegar la cadera del asiento o extender las rodillas con un golpe.', loadEntryConvention: LoadEntryConvention.MACHINE_STACK },
  { name: 'Zancadas con mancuernas', slug: 'zancadas-mancuernas', primaryMuscleGroup: M.QUADRICEPS, secondaryMuscleGroups: [M.GLUTES, M.HAMSTRINGS], equipment: [E.DUMBBELL], movementPattern: P.LUNGE, difficulty: intermediate, description: 'Paso largo alternado con una mancuerna en cada mano y control del equilibrio.', instructions: 'Dá un paso adelante y flexioná ambas rodillas; empujá el suelo para volver manteniendo el tronco estable.', commonMistakes: 'Acortar demasiado el paso o dejar caer el tronco hacia adelante.', loadEntryConvention: LoadEntryConvention.PER_IMPLEMENT, loadMultiplier: 2 },
  { name: 'Peso muerto rumano con barra', slug: 'peso-muerto-rumano', primaryMuscleGroup: M.HAMSTRINGS, secondaryMuscleGroups: [M.GLUTES, M.LOWER_BACK], equipment: [E.BARBELL], movementPattern: P.HINGE, difficulty: intermediate, description: 'Bisagra de cadera con barra y rodillas ligeramente flexionadas.', instructions: 'Llevá la cadera atrás con la barra cerca de las piernas; subí extendiendo la cadera sin perder la espalda estable.', commonMistakes: 'Redondear la espalda o convertir el movimiento en una sentadilla profunda.', aliases: ['rumano', 'rdl'] },
  { name: 'Puente de glúteos', slug: 'puente-gluteos', primaryMuscleGroup: M.GLUTES, secondaryMuscleGroups: [M.HAMSTRINGS], equipment: [E.BODYWEIGHT], movementPattern: P.HINGE, difficulty: basic, description: 'Extensión de cadera desde el suelo con rodillas flexionadas y pies apoyados.', instructions: 'Elevá la cadera hasta alinear hombros y rodillas; descendé despacio manteniendo el apoyo de los pies.', commonMistakes: 'Arquear la espalda en vez de extender la cadera.', performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
  { name: 'Elevación de pantorrillas', slug: 'elevacion-pantorrillas', primaryMuscleGroup: M.CALVES, secondaryMuscleGroups: [], equipment: [E.BODYWEIGHT], movementPattern: P.ISOLATION, difficulty: basic, description: 'Elevación controlada de talones de pie usando el peso corporal.', instructions: 'Elevá los talones, sostené brevemente la posición y bajá de forma controlada.', commonMistakes: 'Rebotar al bajar o inclinar el tronco para generar impulso.', performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
  { name: 'Crunch abdominal', slug: 'crunch-abdominal', primaryMuscleGroup: M.CORE, secondaryMuscleGroups: [], equipment: [E.BODYWEIGHT], movementPattern: P.FLEXION, difficulty: basic, description: 'Flexión corta de tronco desde el suelo, con la zona lumbar apoyada.', instructions: 'Elevá ligeramente el tronco acercando las costillas a la pelvis y volvé al suelo con control.', commonMistakes: 'Tirar de la cabeza con las manos o usar impulso para subir.', performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
  { name: 'Press Pallof en polea', slug: 'press-pallof', primaryMuscleGroup: M.CORE, secondaryMuscleGroups: [M.SHOULDERS], equipment: [E.CABLE], movementPattern: P.ANTI_ROTATION, difficulty: basic, description: 'Empuje frontal de polea resistiendo la rotación del tronco.', instructions: 'Sujetá el agarre frente al pecho, extendé los brazos sin girar el tronco y volvé con control.', commonMistakes: 'Girar el cuerpo hacia la polea o perder el apoyo estable de los pies.', loadEntryConvention: LoadEntryConvention.MACHINE_STACK },
  { name: 'Extensión lumbar en banco', slug: 'extension-lumbar-banco', primaryMuscleGroup: M.LOWER_BACK, secondaryMuscleGroups: [M.GLUTES, M.HAMSTRINGS], equipment: [E.BENCH, E.BODYWEIGHT], movementPattern: P.EXTENSION, difficulty: basic, description: 'Elevación controlada del tronco en un banco de extensión lumbar.', instructions: 'Ajustá el banco a la altura de la cadera; levantá el tronco hasta alinearlo con las piernas y bajá despacio.', commonMistakes: 'Hiperextender la espalda o dejar caer el tronco sin control.', performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
  { name: 'Saltos de tijera', slug: 'saltos-tijera', primaryMuscleGroup: M.FULL_BODY, secondaryMuscleGroups: [M.CALVES, M.SHOULDERS], equipment: [E.BODYWEIGHT], movementPattern: P.CONDITIONING, difficulty: basic, description: 'Apertura y cierre coordinado de brazos y piernas como movimiento de acondicionamiento.', instructions: 'Abrí brazos y piernas al saltar; volvé al centro con una caída suave y un ritmo que puedas controlar.', commonMistakes: 'Caer con rigidez o acelerar sin mantener la coordinación.', performanceMode: ExercisePerformanceMode.REPS_ONLY, loadEntryConvention: null },
];

export function thumbnail(pattern: MovementPattern): string {
  if (pattern === P.HORIZONTAL_PUSH || pattern === P.VERTICAL_PUSH) return '/media/exercises/press.svg';
  if (pattern === P.HORIZONTAL_PULL || pattern === P.VERTICAL_PULL) return '/media/exercises/pull.svg';
  if (pattern === P.SQUAT || pattern === P.LUNGE) return '/media/exercises/squat.svg';
  if (pattern === P.HINGE || pattern === P.EXTENSION) return '/media/exercises/hinge.svg';
  return '/media/exercises/conditioning.svg';
}

export async function seedExercises(db: PrismaClient, organizationId: string, verifierId: string): Promise<void> {
  for (const entry of exerciseSeed) {
    const exercise = await db.exercise.upsert({
      where: { organizationId_slug: { organizationId, slug: entry.slug } }, update: {},
      create: { ...entry, organizationId, aiEligible: true, aliases: entry.aliases ?? [], searchText: normalizeExerciseSearch([entry.name, ...(entry.aliases ?? [])].join(' ')), cautionNotes: 'Si aparece una molestia, detené el movimiento y comentáselo a tu entrenador.', performanceMode: entry.performanceMode ?? ExercisePerformanceMode.WEIGHT_REPS, loadEntryConvention: entry.loadEntryConvention === undefined ? LoadEntryConvention.TOTAL_EXTERNAL_LOAD : entry.loadEntryConvention, loadMultiplier: entry.loadMultiplier ?? 1 },
      select: { id: true, media: { select: { id: true }, take: 1 } },
    });
    if (exercise.media.length > 0) continue;
    const provenance = { organizationId, exerciseId: exercise.id, source: 'PROJECT_ORIGINAL', licenseName: 'Arte original Machi Gym', attributionText: 'Machi Gym · ilustración original', licenseStatus: 'VERIFIED' as const, verifiedAt: new Date(), verifiedByMembershipId: verifierId, active: true };
    await db.exerciseMedia.create({ data: { ...provenance, url: thumbnail(entry.movementPattern), type: 'THUMBNAIL' } });
    if (entry.slug === 'press-militar-barra') await db.exerciseMedia.create({ data: { ...provenance, url: '/media/exercises/press-motion.svg', type: 'ANIMATION' } });
  }
}
