import { Student } from './api';

export type WorkoutStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED' | 'PARTIAL' | 'CANCELLED' | 'SKIPPED';
export type SetState = 'NOT_STARTED' | 'COMPLETED';
export type WorkoutSet = { id: string; setNumber: number; completionState: SetState; actualLoadKg: string | null; actualRepetitions: number | null; rir: number | null; rpe: string | null; completedAt: string | null; version: number; createdAt: string; updatedAt: string };
export type PreviousPerformance = { sessionId: string; finishedAt: string; sets: { setNumber: number; actualLoadKg: string | null; actualRepetitions: number | null; rir: number | null; rpe: string | null }[] };
export type WorkoutExercise = { id: string; exerciseId: string; order: number; exerciseNameSnapshot: string; primaryMuscleSnapshot: string; performanceModeSnapshot: 'WEIGHT_REPS' | 'REPS_ONLY'; loadEntryConventionSnapshot: string | null; loadMultiplierSnapshot: string; instructionsSnapshot: string; commonMistakesSnapshot: string; cautionNotesSnapshot: string | null; targetSets: number; targetRepsMin: number; targetRepsMax: number; intensityMode: 'NONE' | 'RIR' | 'RPE'; targetRir: number | null; targetRpe: string | null; restSeconds: number; trainerNotes: string | null; suggestedLoadKg: string | null; media: { id: string; type: string; url: string; attributionText: string }[]; sets: WorkoutSet[]; previous: PreviousPerformance | null };
export type WorkoutProgress = { totalSets: number; completedSets: number; totalExercises: number; completedExercises: number };
export type WorkoutDetail = { id: string; studentId: string; status: WorkoutStatus; scheduledDate: string; timezone: string; version: number; startedAt: string | null; finishedAt: string | null; cancelledAt: string | null; skippedAt: string | null; partialReason: string | null; partialReasonDetail: string | null; cancellationReason: string | null; workout: { name: string; dayLabel: string | null; expectedDurationMinutes: number | null; planTitle: string }; progress: WorkoutProgress; exercises: WorkoutExercise[]; safetyEvents: { id: string; type: string; bodyRegion: string | null; intensity: number | null; notes: string | null }[] };
export type WorkoutSummary = { id: string; status: WorkoutStatus; scheduledDate: string; timezone: string; startedAt: string | null; finishedAt: string | null; partialReason: string | null; workoutTemplate: { name: string; expectedDurationMinutes: number | null } };
export type WorkoutList = { items: WorkoutSummary[]; nextCursor: string | null };
export type WorkoutHome = { profile: Student; today: { id: string; kind: 'IN_PROGRESS' | 'DUE' | 'UPCOMING'; status: WorkoutStatus; scheduledDate: string; name: string; expectedDurationMinutes: number | null; progress: WorkoutProgress } | null; completedThisWeek: number };
