'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api, StudentRow } from '../../lib/api';
import { SignOut, useSession } from '../../lib/use-session';
import { enumText, t } from '../../lib/i18n';
const enumDiscomfort = (rows: { bodyRegion: string; count: number }[]) => rows.map((row) => `${enumText(row.bodyRegion)}: ${row.count} reportes`).join(', ');
type RosterFact = { adherence: { adherencePercent: number | null; eligible: number; completed: number; partial: number }; averageRpe: number | null; feedbackCount: number; discomfort: { bodyRegion: string; count: number }[] };
function rosterText(fact: RosterFact | undefined) {
  if (!fact) return 'Sin métricas disponibles';
  const adherence = fact.adherence.adherencePercent === null ? 'Sin sesiones elegibles este mes' : `${fact.adherence.completed + fact.adherence.partial}/${fact.adherence.eligible} sesiones · ${fact.adherence.adherencePercent}% adherencia`;
  return `${adherence}${fact.averageRpe === null ? '' : ` · RPE ${fact.averageRpe} (${fact.feedbackCount})`}${fact.discomfort.length ? ` · ${enumDiscomfort(fact.discomfort)}` : ''}`;
}
export default function Trainer() {
  const me = useSession('COACH'); const [students,setStudents] = useState<StudentRow[]>([]); const [name,setName] = useState(''); const [email,setEmail] = useState(''); const [link,setLink] = useState(''); const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  const [mfaUri,setMfaUri] = useState(''); const [mfaCode,setMfaCode] = useState(''); const [recovery,setRecovery] = useState<string[]>([]);
  const [progress, setProgress] = useState<Record<string, { adherence: { adherencePercent: number | null; eligible: number; completed: number; partial: number }; averageRpe: number | null; feedbackCount: number; discomfort: { bodyRegion: string; count: number }[] }>>({});
  useEffect(() => { if (me) api<{ roster: StudentRow[] }>('/trainer/dashboard').then((data) => setStudents(data.roster)).catch((err: unknown) => setError(String(err))); }, [me]);
  useEffect(() => { if (me) void api<{ students: { studentId: string; adherence: { adherencePercent: number | null; eligible: number; completed: number; partial: number }; averageRpe: number | null; feedbackCount: number; discomfort: { bodyRegion: string; count: number }[] }[] }>('/trainer/analytics/roster').then((data) => setProgress(Object.fromEntries(data.students.map((row) => [row.studentId, row])))).catch((err: unknown) => setError(String(err))); }, [me]);
  async function create(event: FormEvent) { event.preventDefault(); setError(''); setBusy(true); try { const result = await api<{ id: string; invitationToken: string; displayName: string }>('/student-invitations', { method: 'POST', body: JSON.stringify({ displayName:name, email }) }); setStudents((rows) => [{ id:result.id, displayName:result.displayName, status:'INCOMPLETE', version:1, onboarded:false }, ...rows]); setLink(`${window.location.origin}/accept?token=${encodeURIComponent(result.invitationToken)}`); setName(''); setEmail(''); } catch(err) { setError(err instanceof Error ? err.message : t('common.error')); } finally { setBusy(false); } }
  async function enroll() { try { const data = await api<{ uri: string }>('/auth/mfa/enroll', { method: 'POST' }); setMfaUri(data.uri); } catch(err) { setError(String(err)); } }
  async function verify() { try { const data = await api<{ recoveryCodes: string[] }>('/auth/mfa/verify', { method: 'POST', body:JSON.stringify({ code:mfaCode }) }); setRecovery(data.recoveryCodes); setMfaUri(''); } catch(err) { setError(String(err)); } }
  if (!me) return <p role="status">{t('trainer.loading')}</p>;
  return <><div className="row wrap hero"><div><div className="eyebrow">{t('trainer.eyebrow')}</div><h1>{t('trainer.greeting', { name:me.displayName })}</h1><p className="muted">{t('trainer.intro')}</p><div className="row wrap"><a className="button secondary" href="/trainer/exercises">{t('catalog.navTrainer')}</a><a className="button secondary" href="/trainer/plans">{t('plans.navTrainer')}</a></div></div><SignOut /></div>{error && <p role="alert" className="error">{error}</p>}
    <div className="grid"><section className="card"><div className="row"><h2>{t('trainer.students')}</h2><span className="badge">{t('trainer.total', { count:students.length })}</span></div><div className="roster">{students.length ? students.map((student) => <a key={student.id} href={`/trainer/students/${student.id}/progress`}><span><strong>{student.displayName}</strong><br/><span className="muted small">{student.onboarded ? t('trainer.active') : t('trainer.pending')} · {rosterText(progress[student.id])}</span></span><span>{t('trainer.view')}</span></a>) : <p className="muted">{t('trainer.empty')}</p>}</div></section>
    <section className="card"><div className="eyebrow">{t('trainer.grow')}</div><h2>{t('trainer.invite')}</h2><p className="muted small">{t('trainer.inviteHelp')}</p><form className="form" onSubmit={create}><label>{t('trainer.studentName')}<input required value={name} onChange={(e)=>setName(e.target.value)} maxLength={120}/></label><label>{t('common.email')}<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} /></label><button className="button" disabled={busy}>{busy ? t('trainer.creating') : t('trainer.create')}</button></form>{link && <div className="notice" role="status"><strong>{t('trainer.link')}</strong><p className="mono small">{link}</p><button className="button secondary" onClick={() => void navigator.clipboard.writeText(link)}>{t('trainer.copy')}</button></div>}</section></div>
    {me.role === 'ADMIN' && !me.mfaEnabled && <section className="card" style={{ marginTop:18 }}><h2>{t('trainer.protect')}</h2><p className="muted">{t('trainer.protectHelp')}</p>{!mfaUri ? <button className="button secondary" onClick={() => void enroll()}>{t('trainer.setupMfa')}</button> : <div className="stack"><p className="mono small">{mfaUri}</p><label>{t('trainer.sixDigits')}<input inputMode="numeric" value={mfaCode} onChange={(e)=>setMfaCode(e.target.value)} /></label><button className="button" onClick={() => void verify()}>{t('trainer.verifyMfa')}</button></div>}{recovery.length > 0 && <div className="notice"><strong>{t('trainer.recovery')}</strong><p className="mono">{recovery.join(' · ')}</p></div>}</section>}
  </>;
}
