import { expect, test } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('biblioteca visual: buscar, filtrar, crear, editar y desactivar; alumno solo consulta', async ({ page, browser }) => {
  const email = process.env.SEED_ADMIN_EMAIL;
  const password = process.env.SEED_ADMIN_PASSWORD;
  if (!email || !password) throw new Error('Configure SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD for E2E');
  const name = `Flexiones guiadas ${randomUUID().slice(0, 6)}`;
  const renamed = `${name} adaptadas`;
  const studentEmail = `catalog-${randomUUID()}@example.test`;
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña').fill(password);
  await page.getByRole('button', { name: 'Ingresar', exact: true }).click();
  await page.getByRole('link', { name: 'Explorar biblioteca →' }).click();
  await expect(page.getByRole('heading', { name: 'Ejercicios para moverse mejor.' })).toBeVisible();
  await expect(page.locator('.exercise-card img').first()).toBeVisible();
  await page.getByLabel('Buscar por nombre o sinónimo').fill('jalon');
  await expect(page.getByRole('heading', { name: 'Jalón al pecho en polea' })).toBeVisible();
  await page.getByLabel('Buscar por nombre o sinónimo').fill('');
  await page.getByLabel('Grupo muscular').selectOption('BACK');
  await page.getByLabel('Equipamiento').selectOption('CABLE');
  await page.getByLabel('Movimiento').selectOption('VERTICAL_PULL');
  await expect(page.getByRole('heading', { name: 'Jalón al pecho en polea' })).toBeVisible();
  await page.getByRole('link', { name: 'Crear ejercicio' }).click();
  await page.getByLabel('Nombre en español').fill(name);
  await page.getByLabel('Descripción').fill('Movimiento de empuje con peso corporal que permite practicar repeticiones controladas.');
  await page.getByLabel('Instrucciones').fill('Apoyá las manos con firmeza y flexioná los codos despacio manteniendo el tronco estable.');
  await page.getByLabel('Errores frecuentes').fill('No uses impulso ni dejes caer la cadera.');
  expect(await page.locator('.exercise-editor :invalid').count()).toBe(0);
  await Promise.all([page.waitForURL(/\/trainer\/exercises\/c[a-z0-9]+$/), page.getByRole('button', { name: 'Guardar ejercicio' }).click()]);
  await expect(page.getByRole('heading', { name })).toBeVisible();
  const exerciseId = page.url().split('/').at(-1);
  if (!exerciseId) throw new Error('Missing exercise ID');
  await page.getByRole('button', { name: 'Editar ejercicio' }).click();
  await page.getByLabel('Nombre en español').fill(renamed);
  await page.getByRole('button', { name: 'Guardar ejercicio' }).click();
  await expect(page.getByRole('heading', { name: renamed })).toBeVisible();

  await page.goto('/trainer');
  await page.getByLabel('Nombre del alumno').fill('Alumno Catálogo');
  await page.getByLabel('Correo electrónico').fill(studentEmail);
  await page.getByRole('button', { name: 'Crear alumno y enlace' }).click();
  const invitation = await page.locator('.notice .mono').first().innerText();
  const student = await browser.newContext();
  try {
    const view = await student.newPage();
    await view.goto(invitation);
    await view.getByLabel('Creá una contraseña').fill('clave-catalogo-prueba-123');
    await view.getByRole('button', { name: 'Crear cuenta' }).click();
    await view.goto('/login');
    await view.getByLabel('Correo electrónico').fill(studentEmail);
    await view.getByLabel('Contraseña').fill('clave-catalogo-prueba-123');
    await view.getByRole('button', { name: 'Ingresar', exact: true }).click();
    await view.getByRole('link', { name: 'Ver ejercicios →' }).click();
    await view.getByLabel('Buscar por nombre o sinónimo').fill('Press militar con barra');
    await view.getByRole('heading', { name: 'Press militar con barra' }).click();
    await expect(view.locator('.detail-visual img')).toHaveAttribute('src', /press-motion\.svg$/);
    await expect(view.getByText('Este recurso es una ilustración de referencia.')).toBeVisible();
    await view.getByRole('link', { name: '← Volver a ejercicios' }).click();
    await view.getByLabel('Buscar por nombre o sinónimo').fill(renamed);
    await view.getByRole('heading', { name: renamed }).click();
    await expect(view.getByRole('heading', { name: 'Cómo realizarlo' })).toBeVisible();
    await expect(view.getByRole('button', { name: 'Editar ejercicio' })).toHaveCount(0);
    const write = await view.request.patch(`/api/v1/exercises/${exerciseId}`, { data: { version: 2, name: 'Inyección' }, headers: { Origin: 'http://localhost:3000' } });
    expect(write.status()).toBe(403);
    page.once('dialog', (dialog) => { void dialog.accept(); });
    await page.goto(`/trainer/exercises/${exerciseId}`);
    await page.getByRole('button', { name: 'Desactivar ejercicio' }).click();
    await expect(page.getByText('Inactivo', { exact: true })).toBeVisible();
    expect((await view.request.get(`/api/v1/exercises/${exerciseId}`)).status()).toBe(404);
  } finally { await student.close(); }
});
