import 'reflect-metadata';
import 'dotenv/config';
import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import { NestFactory } from '@nestjs/core';
import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { createHmac, randomBytes, randomUUID } from 'node:crypto';
import * as argon2 from 'argon2';
import { Db, Envelope, Problems } from './common';
import { AppModule } from './module';

const origin = 'http://localhost:3000';
function sessionCookies(response: request.Response): { cookie: string; csrf: string } {
  const raw = response.headers['set-cookie'] as unknown;
  if (!Array.isArray(raw)) throw new Error('Missing cookies');
  const cookie = raw.map((entry: string) => entry.split(';')[0]).join('; ');
  const csrf = decodeURIComponent((cookie.match(/machi_csrf=([^;]+)/) ?? [])[1] ?? '');
  return { cookie, csrf };
}
describe('Phase 1 trainer → student boundary', () => {
  let app: INestApplication;
  let db: Db;
  let ownerEmail: string;
  let ownerPassword: string;
  let ownerMembership: string;
  let org: string;
  beforeAll(async () => {
    process.env.WEB_ORIGIN = origin;
    app = await NestFactory.create(AppModule, { logger: false });
    app.setGlobalPrefix('api/v1');
    app.useGlobalInterceptors(new Envelope());
    app.useGlobalFilters(new Problems());
    await app.init();
    db = app.get(Db);
    ownerEmail = `coach-${randomUUID()}@example.test`;
    ownerPassword = 'correct horse battery staple';
    const organization = await db.organization.create({ data: { name: 'Test gym' } });
    org = organization.id;
    const user = await db.user.create({ data: { email: ownerEmail, displayName: 'Coach', passwordHash: await argon2.hash(ownerPassword) } });
    const membership = await db.membership.create({ data: { organizationId: org, userId: user.id, role: 'ADMIN' } });
    ownerMembership = membership.id;
    await db.trainerProfile.create({ data: { organizationId: org, membershipId: membership.id } });
  }, 90_000);
  afterAll(async () => { if (app) await app.close(); });

  it('logs in, creates and retrieves a student, accepts invite, and rejects student escalation', async () => {
    const api = request(app.getHttpServer());
    const spec = await api.get('/api/v1/openapi.json').expect(200);
    expect(spec.body.data.paths['/student-invitations'].post.requestBody.content['application/json'].schema.additionalProperties).toBe(false);
    const coachLogin = await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: ownerEmail, password: ownerPassword }).expect(200);
    const coach = sessionCookies(coachLogin);
    const email = `student-${randomUUID()}@example.test`;
    const create = await api.post('/api/v1/student-invitations').set('Origin', origin).set('Cookie', coach.cookie).set('X-CSRF-Token', coach.csrf).send({ email, displayName: 'Alex' }).expect(201);
    const studentId = create.body.data.id as string;
    const read = await api.get(`/api/v1/students/${studentId}`).set('Cookie', coach.cookie).expect(200);
    expect(read.body.data.displayName).toBe('Alex');
    await api.post('/api/v1/auth/accept-invitation').set('Origin', origin).send({ token: create.body.data.invitationToken, password: 'student secret 12345' }).expect(200);
    const studentLogin = await api.post('/api/v1/auth/login').set('Origin', origin).send({ email, password: 'student secret 12345' }).expect(200);
    const student = sessionCookies(studentLogin);
    await api.get('/api/v1/student/me/profile').set('Cookie', student.cookie).expect(200);
    await api.get('/api/v1/trainer/dashboard').set('Cookie', student.cookie).expect(403);
    await api.get(`/api/v1/students/${studentId}`).set('Cookie', student.cookie).expect(403);
    await api.post('/api/v1/student-invitations').set('Cookie', student.cookie).set('Origin', origin).set('X-CSRF-Token', student.csrf).send({ email: 'other@example.test', displayName: 'Other' }).expect(403);
    await api.patch('/api/v1/student/me/profile').set('Cookie', student.cookie).set('Origin', origin).set('X-CSRF-Token', student.csrf).send({ version: 1, status: 'READY' }).expect(400);
    await api.patch('/api/v1/student/me/profile').set('Cookie', student.cookie).set('Origin', origin).set('X-CSRF-Token', 'wrong').send({ version: 1, displayName: 'Eve' }).expect(403);
    const edit = await api.patch('/api/v1/student/me/profile').set('Cookie', student.cookie).set('Origin', origin).set('X-CSRF-Token', student.csrf).send({ version: 1, displayName: 'Alex P' }).expect(200);
    expect(edit.body.data.status).toBe('INCOMPLETE');
    expect(edit.body.data.planningRevision).toBe(2);
    const newConstraint = await api.post('/api/v1/student/me/constraints').set('Cookie', student.cookie).set('Origin', origin).set('X-CSRF-Token', student.csrf).send({ type: 'LIMITATION', description: 'Left knee' }).expect(201);
    expect(newConstraint.body.data.type).toBe('LIMITATION');
    const revised = await db.studentProfile.findUniqueOrThrow({ where: { id: studentId } });
    expect(revised.planningRevision).toBe(3);
    const otherOrg = await db.organization.create({ data: { name: 'Other test gym' } });
    const otherUser = await db.user.create({ data: { email: `other-coach-${randomUUID()}@example.test`, displayName: 'Other coach', passwordHash: await argon2.hash(ownerPassword) } });
    const otherMember = await db.membership.create({ data: { organizationId: otherOrg.id, userId: otherUser.id, role: 'ADMIN' } });
    await db.trainerProfile.create({ data: { organizationId: otherOrg.id, membershipId: otherMember.id } });
    const otherLogin = await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: otherUser.email, password: ownerPassword }).expect(200);
    await api.get(`/api/v1/students/${studentId}`).set('Cookie', sessionCookies(otherLogin).cookie).expect(404);
    const unassignedUser = await db.user.create({ data: { email: `trainer-${randomUUID()}@example.test`, displayName: 'Unassigned', passwordHash: await argon2.hash(ownerPassword) } });
    const unassignedMember = await db.membership.create({ data: { organizationId: org, userId: unassignedUser.id, role: 'TRAINER' } });
    const unassignedProfile = await db.trainerProfile.create({ data: { organizationId: org, membershipId: unassignedMember.id } });
    const unassignedLogin = await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: unassignedUser.email, password: ownerPassword }).expect(200);
    const trainerCookie = sessionCookies(unassignedLogin).cookie;
    await api.get(`/api/v1/students/${studentId}`).set('Cookie', trainerCookie).expect(404);
    const assignment = await db.trainerStudentAssignment.create({ data: { organizationId: org, trainerId: unassignedProfile.id, studentId } });
    await api.get(`/api/v1/students/${studentId}`).set('Cookie', trainerCookie).expect(200);
    await db.trainerStudentAssignment.update({ where: { id: assignment.id }, data: { active: false } });
    await api.get(`/api/v1/students/${studentId}`).set('Cookie', trainerCookie).expect(404);
    const weight = await db.bodyWeightMeasurement.create({ data: { organizationId: org, studentId, recordedByMembershipId: ownerMembership, weightKg: 75, measuredAt: new Date() } });
    await expect(db.bodyWeightMeasurement.update({ where: { id: weight.id }, data: { weightKg: 80 } })).rejects.toThrow();
    await db.membership.update({ where: { id: ownerMembership }, data: { status: 'DISABLED' } });
    await api.get('/api/v1/trainer/dashboard').set('Cookie', coach.cookie).expect(401);
    await api.get('/api/v1/students').set('Cookie', student.cookie).expect(403);
  });
  it('requires MFA after enrollment, rotates sessions, and consumes recovery codes once', async () => {
    process.env.MFA_ENCRYPTION_KEY = randomBytes(32).toString('hex');
    const api = request(app.getHttpServer());
    const user = await db.user.create({ data: { email: `mfa-${randomUUID()}@example.test`, displayName: 'Secure owner', passwordHash: await argon2.hash(ownerPassword) } });
    const organization = await db.organization.create({ data: { name: 'MFA gym' } });
    const membership = await db.membership.create({ data: { organizationId: organization.id, userId: user.id, role: 'ADMIN' } });
    await db.trainerProfile.create({ data: { organizationId: organization.id, membershipId: membership.id } });
    const firstLogin = await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: user.email, password: ownerPassword }).expect(200);
    const first = sessionCookies(firstLogin);
    const enroll = await api.post('/api/v1/auth/mfa/enroll').set('Origin', origin).set('Cookie', first.cookie).set('X-CSRF-Token', first.csrf).expect(201);
    const secret = (enroll.body.data.uri as string).match(/secret=([A-Z2-7]+)/)?.[1];
    if (!secret) throw new Error('Missing TOTP secret');
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; let bits = 0; let value = 0; const bytes: number[] = [];
    for (const char of secret) { value = (value << 5) | alphabet.indexOf(char); bits += 5; if (bits >= 8) { bits -= 8; bytes.push((value >>> bits) & 255); } }
    const counter = Buffer.alloc(8); counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30_000)));
    const digest = createHmac('sha1', Buffer.from(bytes)).update(counter).digest();
    const code = ((digest.readUInt32BE((digest.at(-1) ?? 0) & 15) & 0x7fffffff) % 1_000_000).toString().padStart(6, '0');
    const enabled = await api.post('/api/v1/auth/mfa/verify').set('Origin', origin).set('Cookie', first.cookie).set('X-CSRF-Token', first.csrf).send({ code }).expect(201);
    await api.get('/api/v1/me').set('Cookie', first.cookie).expect(401);
    await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: user.email, password: ownerPassword }).expect(401);
    const recovery = enabled.body.data.recoveryCodes[0] as string;
    await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: user.email, password: ownerPassword, recoveryCode: recovery }).expect(200);
    await api.post('/api/v1/auth/login').set('Origin', origin).send({ email: user.email, password: ownerPassword, recoveryCode: recovery }).expect(401);
  }, 30_000);
});
