import 'reflect-metadata';
import 'dotenv/config';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { NestFactory } from '@nestjs/core';
import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { randomUUID } from 'node:crypto';
import * as argon2 from 'argon2';
import { AppModule } from './module';
import { Db, Envelope, Problems } from './common';
import { seedExercises } from '../prisma/exercises';

const origin = 'http://localhost:3000';
const password = 'workout-test-password-12345';
type Session = { cookie: string; csrf: string };
function session(response: request.Response): Session {
  const raw = response.headers['set-cookie'] as unknown;
  if (!Array.isArray(raw)) throw new Error('Missing login cookies');
  const cookie = raw.map((value: string) => value.split(';')[0]).join('; ');
  return { cookie, csrf: decodeURIComponent((cookie.match(/machi_csrf=([^;]+)/) ?? [])[1] ?? '') };
}
const auth = (who: Session) => ({ Cookie: who.cookie, Origin: origin, 'X-CSRF-Token': who.csrf });
const dateOffset = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);
const setBody = (version: number, completionState: 'NOT_STARTED' | 'COMPLETED', actualLoadKg: string | null, actualRepetitions: number | null, rir: number | null = null) => ({ version, completionState, actualLoadKg, actualRepetitions, rir, rpe: null });

describe('Phase 4 scheduled occurrence and immutable actual execution', () => {
  let app: INestApplication; let db: Db; let coach: Session; let student: Session; let anotherStudent: Session; let otherCoach: Session;
  let studentId: string; let otherStudentId: string; let crossTenantStudentId: string;
  let planId: string; let planVersionId: string; let templateA: string; let templateB: string; let exerciseId: string;
  let firstSessionId: string; let lastSessionId: string; let activeSessionId: string;
  beforeAll(async () => {
    process.env.WEB_ORIGIN = origin;
    app = await NestFactory.create(AppModule, { logger: false }); app.setGlobalPrefix('api/v1'); app.useGlobalInterceptors(new Envelope()); app.useGlobalFilters(new Problems()); await app.init(); db = app.get(Db);
    const org = await db.organization.create({ data: { name: 'Workout integration' } }); const otherOrg = await db.organization.create({ data: { name: 'Other workout org' } });
    async function createUser(organizationId: string, role: 'ADMIN' | 'STUDENT') {
      const email = `workout-${randomUUID()}@example.test`;
      const user = await db.user.create({ data: { email, displayName: role, passwordHash: await argon2.hash(password) } });
      const membership = await db.membership.create({ data: { organizationId, userId: user.id, role } });
      if (role === 'ADMIN') await db.trainerProfile.create({ data: { organizationId, membershipId: membership.id } });
      else await db.studentProfile.create({ data: { organizationId, membershipId: membership.id, displayName: 'Alumno de prueba', contactEmail: email } });
      return { email, membership };
    }
    const owner = await createUser(org.id, 'ADMIN'); const outsider = await createUser(otherOrg.id, 'ADMIN');
    const learner = await createUser(org.id, 'STUDENT'); const peer = await createUser(org.id, 'STUDENT'); const foreign = await createUser(otherOrg.id, 'STUDENT');
    const trainer = await db.trainerProfile.findUniqueOrThrow({ where: { membershipId: owner.membership.id } });
    studentId = (await db.studentProfile.findUniqueOrThrow({ where: { membershipId: learner.membership.id } })).id;
    otherStudentId = (await db.studentProfile.findUniqueOrThrow({ where: { membershipId: peer.membership.id } })).id;
    crossTenantStudentId = (await db.studentProfile.findUniqueOrThrow({ where: { membershipId: foreign.membership.id } })).id;
    for (const id of [studentId, otherStudentId]) await db.trainerStudentAssignment.create({ data: { organizationId: org.id, trainerId: trainer.id, studentId: id } });
    await seedExercises(db, org.id, owner.membership.id);
    const api = request(app.getHttpServer());
    const login = async (email: string) => session(await api.post('/api/v1/auth/login').set('Origin', origin).send({ email, password }).expect(200));
    coach = await login(owner.email); student = await login(learner.email); anotherStudent = await login(peer.email); otherCoach = await login(outsider.email);
    const plan = await api.post('/api/v1/training-plans').set(auth(coach)).send({ name: 'Fuerza supervisada', goal: 'STRENGTH' }).expect(201);
    planId = plan.body.data.id as string; planVersionId = plan.body.data.versions[0].id as string;
    const workout = await api.post(`/api/v1/plan-versions/${planVersionId}/workouts`).set(auth(coach)).send({ revision: 1, name: 'Full Body A', expectedDurationMinutes: 45 }).expect(201);
    templateA = workout.body.data.workouts[0].id as string;
    const workoutTwo = await api.post(`/api/v1/plan-versions/${planVersionId}/workouts`).set(auth(coach)).send({ revision: 2, name: 'Full Body B' }).expect(201);
    templateB = workoutTwo.body.data.workouts[1].id as string;
    exerciseId = (await db.exercise.findUniqueOrThrow({ where: { organizationId_slug: { organizationId: org.id, slug: 'press-banca-barra' } } })).id;
    const repsId = (await db.exercise.findUniqueOrThrow({ where: { organizationId_slug: { organizationId: org.id, slug: 'flexiones-brazos' } } })).id;
    const entryA = await api.post(`/api/v1/workout-templates/${templateA}/exercises`).set(auth(coach)).send({ revision: 3, exerciseId, targetSets: 2, targetRepsMin: 8, targetRepsMax: 10, intensityMode: 'RIR', targetRir: 2, restSeconds: 90, suggestedLoadKg: '90.00' }).expect(201);
    const entryB = await api.post(`/api/v1/workout-templates/${templateA}/exercises`).set(auth(coach)).send({ revision: entryA.body.data.revision, exerciseId: repsId, targetSets: 1, targetRepsMin: 8, targetRepsMax: 12, intensityMode: 'NONE', restSeconds: 60 }).expect(201);
    const third = await api.post(`/api/v1/workout-templates/${templateB}/exercises`).set(auth(coach)).send({ revision: entryB.body.data.revision, exerciseId: repsId, targetSets: 1, targetRepsMin: 8, targetRepsMax: 12, intensityMode: 'NONE', restSeconds: 60 }).expect(201);
    await api.post(`/api/v1/plan-versions/${planVersionId}/publish`).set(auth(coach)).send({ revision: third.body.data.revision }).expect(201);
    for (const id of [studentId, otherStudentId]) await api.post(`/api/v1/students/${id}/plan-assignment`).set(auth(coach)).send({ planId, startDate: dateOffset(-7) }).expect(201);
  }, 90_000);
  afterAll(async () => { if (app) await app.close(); });

  it('schedules exact immutable snapshots, rejects tenant misuse, and idempotently starts/resumes', async () => {
    const api = request(app.getHttpServer());
    const key = randomUUID();
    await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(student)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(-2), requestKey: key }).expect(403);
    await api.post(`/api/v1/students/${crossTenantStudentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(-2), requestKey: randomUUID() }).expect(404);
    await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(otherCoach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(-2), requestKey: randomUUID() }).expect(404);
    const created = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(-2), requestKey: key }).expect(201);
    firstSessionId = created.body.data.id as string;
    expect(created.body.data.status).toBe('NOT_STARTED');
    expect(created.body.data.exercises).toHaveLength(2);
    expect(created.body.data.exercises[0].sets).toHaveLength(2);
    expect(created.body.data.exercises[0].sets[0].actualLoadKg).toBeNull();
    expect(Number(created.body.data.exercises[0].suggestedLoadKg)).toBe(90);
    expect((await db.workoutSession.findUniqueOrThrow({ where: { id: firstSessionId } })).snapshotSealed).toBe(true);
    const repeat = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(-2), requestKey: key }).expect(201);
    expect(repeat.body.data.id).toBe(firstSessionId);
    await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateB, scheduledDate: dateOffset(-2), requestKey: key }).expect(409);
    await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', anotherStudent.cookie).expect(404);
    await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', otherCoach.cookie).expect(404);
    await api.post(`/api/v1/workout-sessions/${firstSessionId}/start`).set(auth(anotherStudent)).send({}).expect(404);
    await api.post(`/api/v1/workout-sessions/${firstSessionId}/start`).set(auth(coach)).send({}).expect(403);
    const start = await api.post(`/api/v1/workout-sessions/${firstSessionId}/start`).set(auth(student)).send({}).expect(201);
    expect(start.body.data.status).toBe('IN_PROGRESS');
    const startedAt = start.body.data.startedAt as string;
    const retried = await api.post(`/api/v1/workout-sessions/${firstSessionId}/start`).set(auth(student)).send({}).expect(201);
    expect(retried.body.data.startedAt).toBe(startedAt);
    expect(await db.workoutSession.count({ where: { id: firstSessionId } })).toBe(1);
    await db.exercise.update({ where: { id: exerciseId }, data: { name: 'Press de pecho actualizado', version: { increment: 1 } } });
    expect((await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', student.cookie).expect(200)).body.data.exercises[0].exerciseNameSnapshot).toBe('Press de banca con barra');
    await expect(db.sessionExercise.update({ where: { id: start.body.data.exercises[0].id }, data: { targetSets: 4 } })).rejects.toThrow();
    const second = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateB, scheduledDate: dateOffset(-1), requestKey: randomUUID() }).expect(201);
    await api.post(`/api/v1/workout-sessions/${second.body.data.id}/start`).set(auth(student)).send({}).expect(409);
  }, 40_000);

  it('persists actuals, permits in-progress correction, finishes fully and supplies batched previous sets', async () => {
    const api = request(app.getHttpServer());
    const detail = await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', student.cookie).expect(200);
    const [weighted, bodyweight] = detail.body.data.exercises;
    const setId = weighted.sets[0].id as string;
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(anotherStudent)).send(setBody(1, 'COMPLETED', '40.00', 8, 2)).expect(404);
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(student)).send({ ...setBody(1, 'COMPLETED', '40.00', 8, 2), targetSets: 99 }).expect(400);
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${bodyweight.sets[0].id}`).set(auth(student)).send(setBody(1, 'COMPLETED', '40.00', 10)).expect(400);
    const draft = await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(student)).send(setBody(1, 'NOT_STARTED', '40.00', 8, 2)).expect(200);
    expect(draft.body.data.set.completionState).toBe('NOT_STARTED');
    const completed = await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(student)).send(setBody(2, 'COMPLETED', '40.00', 8, 2)).expect(200);
    expect(completed.body.data.progress.completedSets).toBe(1);
    const edited = await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(student)).send(setBody(3, 'COMPLETED', '42.50', 9, 1)).expect(200);
    expect(Number(edited.body.data.set.actualLoadKg)).toBe(42.5);
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(student)).send(setBody(3, 'COMPLETED', '10.00', 3, 1)).expect(409);
    const resumed = await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', student.cookie).expect(200);
    expect(Number(resumed.body.data.exercises[0].sets[0].actualLoadKg)).toBe(42.5);
    expect(resumed.body.data.progress.completedExercises).toBe(0);
    await api.post(`/api/v1/workout-sessions/${firstSessionId}/cancel`).set(auth(student)).send({ version: resumed.body.data.version, reason: 'OTHER' }).expect(409);
    await api.post(`/api/v1/workout-sessions/${firstSessionId}/finish`).set(auth(student)).send({ version: resumed.body.data.version }).expect(400);
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${weighted.sets[1].id}`).set(auth(student)).send(setBody(1, 'COMPLETED', '35.00', 8, 2)).expect(200);
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${bodyweight.sets[0].id}`).set(auth(student)).send(setBody(1, 'COMPLETED', null, 12)).expect(200);
    const all = await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', student.cookie).expect(200);
    expect(all.body.data.progress).toEqual({ totalSets: 3, completedSets: 3, totalExercises: 2, completedExercises: 2 });
    const finished = await api.post(`/api/v1/workout-sessions/${firstSessionId}/finish`).set(auth(student)).send({ version: all.body.data.version }).expect(201);
    expect(finished.body.data.status).toBe('COMPLETED');
    await api.post(`/api/v1/workout-sessions/${firstSessionId}/finish`).set(auth(student)).send({ version: all.body.data.version }).expect(201);
    await api.put(`/api/v1/workout-sessions/${firstSessionId}/sets/${setId}`).set(auth(student)).send(setBody(4, 'COMPLETED', '80.00', 10, 2)).expect(409);
    await expect(db.setPerformance.update({ where: { id: setId }, data: { actualRepetitions: 100 } })).rejects.toThrow();
    await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', coach.cookie).expect(200);
    await api.get(`/api/v1/workout-sessions/${firstSessionId}`).set('Cookie', otherCoach.cookie).expect(404);
    await api.post(`/api/v1/students/${crossTenantStudentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(0), requestKey: randomUUID() }).expect(404);
    const plan = await db.trainingPlan.findUniqueOrThrow({ where: { id: planId } });
    const revised = await api.post(`/api/v1/training-plans/${planId}/versions`).set(auth(coach)).send({ planVersion: plan.version }).expect(201);
    await api.post(`/api/v1/plan-versions/${revised.body.data.id}/publish`).set(auth(coach)).send({ revision: revised.body.data.revision }).expect(201);
    expect((await db.trainingPlanVersion.findUniqueOrThrow({ where: { id: planVersionId } })).status).toBe('RETIRED');
    const later = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(0), requestKey: randomUUID() }).expect(201);
    lastSessionId = later.body.data.id as string;
    expect(later.body.data.exercises[0].exerciseNameSnapshot).toBe('Press de banca con barra');
    const startedLater = await api.post(`/api/v1/workout-sessions/${lastSessionId}/start`).set(auth(student)).send({}).expect(201);
    expect(startedLater.body.data.exercises[0].previous.sets).toHaveLength(2);
    expect(Number(startedLater.body.data.exercises[0].previous.sets[0].actualLoadKg)).toBe(42.5);
    expect(startedLater.body.data.exercises[0].sets[0].actualLoadKg).toBeNull();
    expect(Number(startedLater.body.data.exercises[0].suggestedLoadKg)).toBe(90);
    activeSessionId = lastSessionId;
  }, 40_000);

  it('finishes a valid partial with canonical discomfort fact and leaves incomplete sets intact', async () => {
    const api = request(app.getHttpServer());
    const current = await api.get(`/api/v1/workout-sessions/${activeSessionId}`).set('Cookie', student.cookie).expect(200);
    const firstSet = current.body.data.exercises[0].sets[0];
    await api.put(`/api/v1/workout-sessions/${activeSessionId}/sets/${firstSet.id}`).set(auth(student)).send(setBody(1, 'COMPLETED', '30.00', 6, 3)).expect(200);
    const beforeFinish = await api.get(`/api/v1/workout-sessions/${activeSessionId}`).set('Cookie', student.cookie).expect(200);
    expect(beforeFinish.body.data.progress.completedSets).toBe(1);
    await api.post(`/api/v1/workout-sessions/${activeSessionId}/finish`).set(auth(student)).send({ version: beforeFinish.body.data.version }).expect(400);
    const finishBody = { version: beforeFinish.body.data.version, partialReason: 'DISCOMFORT_OR_PAIN', bodyRegion: 'RIGHT_KNEE', intensity: 4, partialReasonDetail: 'Molestia al bajar' };
    const partial = await api.post(`/api/v1/workout-sessions/${activeSessionId}/finish`).set(auth(student)).send(finishBody).expect(201);
    expect(partial.body.data.status).toBe('PARTIAL');
    expect(partial.body.data.progress.completedSets).toBe(1);
    expect(partial.body.data.safetyEvents).toHaveLength(1);
    expect(partial.body.data.safetyEvents[0].bodyRegion).toBe('RIGHT_KNEE');
    await api.post(`/api/v1/workout-sessions/${activeSessionId}/finish`).set(auth(student)).send(finishBody).expect(201);
    expect(await db.sessionSafetyEvent.count({ where: { workoutSessionId: activeSessionId } })).toBe(1);
    await api.put(`/api/v1/workout-sessions/${activeSessionId}/sets/${firstSet.id}`).set(auth(student)).send(setBody(2, 'COMPLETED', '99.00', 10, 1)).expect(409);
    await expect(db.workoutSession.update({ where: { id: activeSessionId }, data: { partialReason: 'OTHER' } })).rejects.toThrow();
    const other = await api.post(`/api/v1/students/${otherStudentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateA, scheduledDate: dateOffset(0), requestKey: randomUUID() }).expect(201);
    const otherStarted = await api.post(`/api/v1/workout-sessions/${other.body.data.id}/start`).set(auth(anotherStudent)).send({}).expect(201);
    expect(otherStarted.body.data.exercises[0].previous).toBeNull();
    await api.get(`/api/v1/workout-sessions/${other.body.data.id}`).set('Cookie', student.cookie).expect(404);
  }, 40_000);

  it('keeps abandonment resumable and distinguishes explicit cancellation from past-due skipped', async () => {
    const api = request(app.getHttpServer());
    const future = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateB, scheduledDate: dateOffset(2), requestKey: randomUUID() }).expect(201);
    const futureId = future.body.data.id as string;
    await api.post(`/api/v1/workout-sessions/${futureId}/start`).set(auth(student)).send({}).expect(409);
    await api.post(`/api/v1/workout-sessions/${futureId}/skip`).set(auth(coach)).send({ version: 1 }).expect(409);
    await api.post(`/api/v1/workout-sessions/${futureId}/skip`).set(auth(student)).send({ version: 1 }).expect(403);
    const cancelled = await api.post(`/api/v1/workout-sessions/${futureId}/cancel`).set(auth(student)).send({ version: 1, reason: 'SCHEDULE_CHANGE' }).expect(201);
    expect(cancelled.body.data.status).toBe('CANCELLED');
    await api.post(`/api/v1/workout-sessions/${futureId}/cancel`).set(auth(student)).send({ version: 1, reason: 'SCHEDULE_CHANGE' }).expect(201);
    const past = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateB, scheduledDate: dateOffset(-4), requestKey: randomUUID() }).expect(201);
    const skipped = await api.post(`/api/v1/workout-sessions/${past.body.data.id}/skip`).set(auth(coach)).send({ version: 1 }).expect(201);
    expect(skipped.body.data.status).toBe('SKIPPED');
    const started = await api.post(`/api/v1/students/${studentId}/workout-sessions`).set(auth(coach)).send({ workoutTemplateId: templateB, scheduledDate: dateOffset(0), requestKey: randomUUID() }).expect(201);
    const inProgress = await api.post(`/api/v1/workout-sessions/${started.body.data.id}/start`).set(auth(student)).send({}).expect(201);
    const afterReload = await api.get(`/api/v1/workout-sessions/${started.body.data.id}`).set('Cookie', student.cookie).expect(200);
    expect(afterReload.body.data.status).toBe('IN_PROGRESS');
    expect(afterReload.body.data.startedAt).toBe(inProgress.body.data.startedAt);
    await api.post(`/api/v1/workout-sessions/${started.body.data.id}/cancel`).set(auth(student)).send({ version: inProgress.body.data.version, reason: 'FEELING_UNWELL' }).expect(201);
  }, 40_000);
});
